#!/bin/bash
##AUTHOR: crunchie
##DATE: 08.12.2019
##set_apt-sources.sh - Change content of /etc/apt/sources.list depending on whether local aptcache-server is available
##Version: 2.3
## CHANGES V2.0: variables os and version are now automatically determined. Added comments to sources.list for seperate repositories. Added customization for raspbian and debian for stretch and jessie.
## Added check for whether executing user is root. Minor optimizations.
## CHANGES V2.1: Defined function for creating different apt-sources-files. Using variables for defining sources instead of release-version-specific strings.
## CHANGES V2.2: Added Syncthing-Source and Source-Key-Install. Added curl-Install. Corrected spelling error in variable-usage that led to faulty execution.
## CHANGES V2.3: Changed method to determine release, version and distribution.

######################
## RASPBIAN SOURCES ##
######################

set_raspbian_source () {

if [ "$1" == "lokal" ]; then
    echo "deb http://$server:$port/$rasp_url/$distri/ $release main contrib non-free rpi" >> /etc/apt/sources.list
elif [ "$1" == "remote" ]; then
    echo "deb http://$rasp_url/$distri/ $release main contrib non-free rpi" >> /etc/apt/sources.list
fi
}

####################
## DEBIAN SOURCES ##
####################

set_debian_source () {

if [ "$1" == "lokal" ]; then
    echo "# $release non-free" >> /etc/apt/sources.list
    echo "deb http://$server:$port/$deb_url/$distri/ $release main non-free" >> /etc/apt/sources.list
    echo "deb-src http://$server:$port/$deb_url/$distri/ $release main non-free" >> /etc/apt/sources.list
	echo "" >> /etc/apt/sources.list
    echo "# $release security" >> /etc/apt/sources.list
    echo "deb http://$server:$port/security.debian.org/debian-security $release/updates main contrib" >> /etc/apt/sources.list
    echo "deb-src http://$server:$port/security.debian.org/debian-security $release/updates main contrib" >> /etc/apt/sources.list
	echo "" >> /etc/apt/sources.list
    echo "# $release-updates, previously know as 'volatile'" >> /etc/apt/sources.list
    echo "deb http://$server:$port/$deb_url/$distri/ $release-updates main contrib" >> /etc/apt/sources.list
    echo "deb-src http://$server:$port/$deb_url/$distri/ $release-updates main contrib" >> /etc/apt/sources.list

elif [ "$1" == "remote" ]; then
    echo "# $release non-free" >> /etc/apt/sources.list
    echo "deb http://$deb_url/$distri/ $release main non-free" >> /etc/apt/sources.list
    echo "deb-src http://$deb_url/$distri/ $release main non-free" >> /etc/apt/sources.list
	echo "" >> /etc/apt/sources.list    
    echo "# $release security" >> /etc/apt/sources.list
    echo "deb http://security.debian.org/debian-security $release/updates main contrib" >> /etc/apt/sources.list
    echo "deb-src http://security.debian.org/debian-security $release/updates main contrib" >> /etc/apt/sources.list
	echo "" >> /etc/apt/sources.list    
    echo "# $release-updates, previously know as 'volatile'" >> /etc/apt/sources.list
    echo "deb http://$deb_url/$distri/ $release-updates main contrib" >> /etc/apt/sources.list
    echo "deb-src http://$deb_url/$distri/ $release-updates main contrib" >> /etc/apt/sources.list
fi
}

set_syncthing () {
if [ "$1" == "lokal" ]; then
	echo "" >> /etc/apt/sources.list    
	echo "#Syncthing" >> /etc/apt/sources.list
	echo "deb http://$server:$port/apt.syncthing.net/ syncthing release" >> /etc/apt/sources.list
elif [ "$1" == "remote" ]; then
	echo "" >> /etc/apt/sources.list
	echo "#Syncthing" >> /etc/apt/sources.list
	echo "deb http://apt.syncthing.net/ syncthing release" >> /etc/apt/sources.list
fi
}

#######################
## GENERAL FUNCTIONS ##
#######################

rm_original_source () {

if [ -d /etc/orig ]; then
    mv /etc/apt/sources.list /etc/orig
    touch /etc/apt/sources.list
	echo "########################################################################" >> /etc/apt/sources.list
    echo "## This file was created via script! Please do not edit file by hand! ##" >> /etc/apt/sources.list
	echo "########################################################################" >> /etc/apt/sources.list
	echo "" >> /etc/apt/sources.list
elif [ ! -d /etc/orig ]; then
    mkdir -p /etc/orig
    mv /etc/apt/sources.list /etc/orig
    touch /etc/apt/sources.list
	echo "########################################################################" >> /etc/apt/sources.list
    echo "## This file was created via script! Please do not edit file by hand! ##" >> /etc/apt/sources.list
	echo "########################################################################" >> /etc/apt/sources.list
	echo "" >> /etc/apt/sources.list
fi
}

set_new_file () {
# Check whether the defined server is available - source for ping-command: https://stackoverflow.com/questions/8937663/shell-script-to-check-wether-a-server-is-reachable
ping_server $server status
if [ $status == 0 ] ; then
	if [ $2 == "stdsrc" ]; then
		set_$1_source lokal       
	elif [ $2 == "syncthing" ]; then
		set_syncthing lokal
	fi
else
	if [ $2 == "stdsrc" ]; then
		set_$1_source remote      
	elif [ $2 == "syncthing" ]; then
		set_syncthing remote
	fi
fi
}

install_key_syncthing () {
    apt-get install -y curl
    curl -s https://syncthing.net/release-key.txt | apt-key add -
}

get_release () {
codename=$(cat /etc/*-release | grep VERSION_CODENAME= | sed -r 's/.{17}//') # Only works on buster or later.
if [ $? == 0 ]; then
	release=$codename
else
	releasenr=$(cat /etc/*-release | grep VERSION_ID= | sed -r 's/.{12}//' | sed -r 's/.{1}$//')
	case $releasenr in
		7)		release="wheezy"
				;;
		8)		release="jessie"
				;;
		9)		release="stretch"
				;;
		10)		release="buster"
				;;
		*)		echo "No valid Version ID could be determined."
				exit 1
				;;	
	esac
fi
}

get_version () {
version=$(cat /etc/*-release | grep -w VERSION | sed -r 's/.{9}//' | sed -r 's/.{1}$//')
}

get_distribution () {
distri=$(cat /etc/os-release | grep -w "ID" | sed -r 's/.{3}//' | tr '[:upper:]' '[:lower:]')
}

ping_server () {
local -n lpingable=$2
ping -c1 -W1 -q $1 &>/dev/null
lpingable=$?
}

###################
## EXECUTE BLOCK ##
###################

# Check if executing User is root, if not --> exit with error!
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
get_distribution
get_release
get_version

# Set variables; server=IP of apt-cache-server;
deb_url="debian.lagis.at"               # BASE-URL of closest debian-mirror use netselect-apt -c [COUNTRY] -t 15 -a amd64 -n testing or https://www.debian.org/mirror/list to find closes/best server.
rasp_url="mirrordirector.raspbian.org"  # BASE-URL of RASPBIAN mirror
server=10.10.60.6                      	# IP/FQDN of used  apt-cache-server
port=3142                               # PORT of used apt-cache-server
system=$distri"-"$release

case $distri in
    "debian" | "raspbian") 
        rm_original_source
		set_new_file $distri stdsrc
		apt-get update
		apt-get install curl gpg2
		set_new_file $distri syncthing
		install_key_syncthing
		apt-get update
        ;;
    *)  
        # Do nothing, as no sources are defined.
        echo "THIS SCRIPT WAS DESIGNED FOR DEBIAN AND RASPBIAN DISTRIBUTIONS ONLY. NOTHING WAS CHANGED!"
        ;;
esac 
exit 0 
